#!/bin/sh
# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: MIT

kded5&
sleep 7

qdbus org.kde.kded5 /modules/kscreen org.kde.KScreen.setAutoRotate false
kde-inhibit --screenSaver --power pico-wizard
